version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: airbnb-backend
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=airbnb-database;Username=admin;Password=adminpassword
    ports:
      - "5013:8080"
    networks:
      - airbnb-network

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: airbnb-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge

volumes:
  pgdata: